codecov:
  # strict_yaml_branch: "yaml-config"
  # max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  # notify:
  #   after_n_builds: 2
  #   wait_for_ci: yes
  
fixes:
  - "/home/runner/work/pylimer-tools/::"

ignore:
  - "docs/*"
  - "docs-template/*"
  - "tests/__init__.py"
  - "tests/pylimer*/*"
  - "tests/pylimer*/**/*"
  - "tests/pylimer_tools/__init__.py"
  - "setup.py"
  - "update-all.py"
  - "pyproject.toml"


comment:
  layout: "header, diff, flags, components"  # show component info in the PR comment
  
component_management:
  default_rules:  # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doesn't have a status defined will have a project type one
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: module_cpp  # this is an identifier that should not be changed
      name: C++ Code  # this is a display name, and can be changed freely
      paths:
        - src/pylimer_tools_cpp/**
    - component_id: module_python
      name: Python Code
      paths:
        - src/pylimer_tools/**
