name: Publish Windows Version to PyPi

on:
  push:
    tags:
      - "v*"

jobs:
  build-deploy:
    runs-on: windows-latest

    name: Build & Publish Package
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Install additional dependencies
        run: pip install wheel build twine

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Install choco dependencies
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install winflexbison

      - name: Build
        run: ./bin/build.sh

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
