name: Publish Different Version to PyPi
# inspired partially by https://github.com/ansible/pylibssh/blob/206c222ee8ee2cdb2b5dc9b95125f7f3d27d32bc/.github/workflows/build-test-n-publish.yml

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest

    name: Build 📦 for Windows and 🐍 ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.11"
          - "3.10"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v3
        with:
          path: |
            ~\AppData\Local\pip\Cache
            ~\AppData\Local\Temp\chocolatey
            .\vendor\igraph
            .\vendor\nlopt
            .\_skbuild
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Install choco dependencies
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install -y winflexbison3 eigen

      - name: Build
        run: python -m build --wheel
        env:
          CI: true
          CMAKE_BUILD_TYPE: Release

      - name: Store the build
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions-windows-${{ matrix.python-version }}
          path: dist
          retention-days: 3

  build-osx:
    runs-on: macos-latest
    name: Build 📦 for MacOS and 🐍 ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version:
          # NOTE: https://github.com/MacPython/wiki/wiki/Spinning-wheels
          - "3.12"
          - "3.11"
          - "3.10"
          - 3.9

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/pip
            ./vendor/igraph
            ./vendor/igraph-skbuild
            ./vendor/nlopt
            ./vendor/nlopt-skbuild
            ./vendor/cereal
            ./vendor/cereal-skbuild
            ./_skbuild
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Install additional dependencies
        run: brew install bison flex libomp

      - name: Build
        run: ./bin/build-wheel.sh
        env:
          CI: true
          CMAKE_BUILD_TYPE: Release

      - name: Store the build
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions-macos-${{ matrix.python-version }}
          path: dist
          retention-days: 3

  # inspired by https://github.com/igraph/python-igraph/blob/a039f5d6e5fc705458ffa966e3ec5fcbb4985f03/.github/workflows/build.yml
  build_wheel_wasm:
    name: Build wheels for WebAssembly
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version: "3.12"

      - name: Install OS dependencies
        run: sudo apt install ninja-build cmake flex bison libeigen3-dev python3-dev

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: "3.1.58"
          actions-cache-folder: "emsdk-cache"

      - name: Set CMAKE_PREFIX_PATH
        run: echo "CMAKE_PREFIX_PATH=$(python3 -c 'import sys; print(sys.prefix)')" >> $GITHUB_ENV

      - name: Build wheel
        run: |
          pip install pyodide-build==0.26.2
          python3 bin/fix_pyodide_build.py
          pyodide build
        env:
          CI: true
          CMAKE_BUILD_TYPE: Release
          CMAKE_PREFIX_PATH: ${{ env.CMAKE_PREFIX_PATH }}

      - name: Store the build
        uses: actions/upload-artifact@v4
        with:
          name: wheels-wasm
          path: ./dist/*.whl

  build-linux:
    runs-on: ubuntu-latest
    name: Build 📦 for ManyLinux

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version: "3.12"

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ./vendor/igraph
            ./vendor/igraph-skbuild
            ./vendor/nlopt
            ./vendor/nlopt-skbuild
            ./vendor/cereal
            ./vendor/cereal-skbuild
            ./_skbuild
          key: ${{ runner.os }}-pip-3.12-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-3.12-

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Build manylinux Python wheels
        run: cibuildwheel --output-dir dist --platform linux
        env:
          CIBW_BUILD: cp39-* cp310-* cp311-* cp312-*
          CIBW_ARCHS_LINUX: x86_64
          CIBW_BUILD_VERBOSITY: 1
          CIBW_SKIP: "*musllinux*"

      - name: Store the build
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions-linux
          path: dist
          retention-days: 3

  build-sdist:
    runs-on: ubuntu-latest
    name: Build SRC Package for Any

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build Sdist
        run: ./bin/build-sdist.sh
        env:
          CI: true
          CMAKE_BUILD_TYPE: Release

      - name: Store the build
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions-sdist
          path: dist
          retention-days: 3

  deploy:
    runs-on: ubuntu-latest
    name: Publish 🐍📦 to PyPI
    needs:
      - build-windows
      - build-osx
      # - build_wheel_wasm
      - build-linux
      - build-sdist
    environment:
      name: pypi
      url: https://pypi.org/p/pylimer-tools
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing
    if: startsWith(github.ref, 'refs/tags/') # only create GitHub release on tag push

    steps:
      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: python-package-distributions-windows-*
          path: dist/
          merge-multiple: true

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: python-package-distributions-macos-*
          path: dist/
          merge-multiple: true

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions-linux
          path: dist/

      - name: Download sdist artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions-sdist
          path: dist/

      - name: List and delete invalid packages
        run: |
          ls dist/*-linux_*
          rm dist/*-linux_*

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  deploy_test:
    runs-on: ubuntu-latest
    name: Publish 🐍📦 to TestPyPI
    needs:
      - build-windows
      - build-osx
      # - build_wheel_wasm
      - build-linux
      - build-sdist
    environment:
      name: testpypi
      url: https://test.pypi.org/p/pylimer-tools/
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: python-package-distributions-windows-*
          path: dist/
          merge-multiple: true

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: python-package-distributions-macos-*
          path: dist/
          merge-multiple: true

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions-linux
          path: dist/

      - name: Download sdist artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions-sdist
          path: dist/

      - name: List and delete invalid packages
        run: |
          ls dist/*-linux_*
          rm dist/*-linux_*

      - name: Publish a Python distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  github_release:
    runs-on: ubuntu-latest
    name: Create GitHub Release
    needs:
      - build-windows
      - build-osx
      # - build_wheel_wasm
      - build-linux
      - build-sdist
    if: startsWith(github.ref, 'refs/tags/') # only create GitHub release on tag push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-tags: true

      - name: Get tag
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV

      - name: Determine Changelog
        id: changelog_determiner
        run: echo "##[set-output name=changelog;]$(./bin/extract-changelog.sh CHANGELOG.md $GIT_TAG)"

      - name: Create Release
        id: create_release
        if: success()
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog_determiner.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: python-package-distributions-windows-*
          path: dist/
          merge-multiple: true

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: python-package-distributions-macos-*
          path: dist/
          merge-multiple: true

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions-linux
          path: dist/

      # - name: Download WASM artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: wheels-wasm
      #     path: dist/

      - name: Download sdist artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions-sdist
          path: dist/

      - name: Upload Release
        id: upload_release
        if: success()
        uses: csexton/release-asset-action@v2
        with:
          pattern: "dist/*.*"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
